version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "go_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - ./zephyr.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://postgres:123@db:5432/go_db?sslmode=disable
    depends_on:
      - db
    entrypoint: ["sh", "-c", "sleep 10 && ./main"]
