--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

-- Started on 2024-10-25 19:50:03 +05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 229 (class 1255 OID 16691)
-- Name: generate_unique_code(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.generate_unique_code() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    new_code INT;
    attempt_count INT := 0;
    max_attempts INT := 50; -- Number of unique codes between 1000 and 9999 (inclusive)
BEGIN
    -- Generate a random code between 1000 and 9999 and check if it already exists
    LOOP
        new_code := FLOOR(RANDOM() * (9999 - 1000 + 1)) + 1000;

        -- Check if the code is already in the table
        IF NOT EXISTS (SELECT 1 FROM users WHERE code = new_code) THEN
            EXIT; -- Exit the loop if the code is unique
        END IF;
        
        -- Increment the attempt count
        attempt_count := attempt_count + 1;

        -- If we've attempted more than the max possible unique codes, raise an exception
        IF attempt_count >= max_attempts THEN
            RAISE EXCEPTION 'No available unique codes in the range 1000-9999';
        END IF;
    END LOOP;

    -- Assign the new unique code to the new row
    NEW.code := new_code;
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.generate_unique_code() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16599)
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id integer NOT NULL,
    name character varying NOT NULL,
    parent_id integer
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16598)
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16651)
-- Name: food; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.food (
    id integer NOT NULL,
    category_id integer,
    name character varying NOT NULL,
    price integer NOT NULL,
    max_quantity integer
);


ALTER TABLE public.food OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16650)
-- Name: food_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.food ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.food_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16663)
-- Name: food_products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.food_products (
    food_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer
);


ALTER TABLE public.food_products OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16643)
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id integer NOT NULL,
    name character varying NOT NULL,
    in_stock integer NOT NULL,
    unit character varying NOT NULL
);


ALTER TABLE public.products OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16642)
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16744)
-- Name: tables; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tables (
    number integer NOT NULL,
    position_x double precision NOT NULL,
    position_y double precision NOT NULL,
    size_width double precision NOT NULL,
    size_height double precision NOT NULL,
    occupied boolean DEFAULT false
);


ALTER TABLE public.tables OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16516)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    username character varying NOT NULL,
    password character varying NOT NULL,
    code integer NOT NULL,
    role character varying
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16515)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3637 (class 0 OID 16599)
-- Dependencies: 218
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categories (id, name, parent_id) FROM stdin;
24	кухня	\N
25	мангал	\N
26	бар	\N
27	Европейская кухня	24
28	Китайская кухня	24
29	Грузинская кухня	24
30	Алкогольные	26
31	Безалкогольные	26
32	Коктейли	26
33	Лимонады	26
34	супы	27
45	Kira I	28
50	Fjdskljflks	25
61	Narnarnbarb	26
\.


--
-- TOC entry 3641 (class 0 OID 16651)
-- Dependencies: 222
-- Data for Name: food; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.food (id, category_id, name, price, max_quantity) FROM stdin;
7	27	Альфредо	3290	20
8	27	Пельмени	3290	20
9	28	Фри с мясом	3290	20
10	28	Ганбян чайзи	3290	20
11	32	Cosmopolitan	3590	10
12	32	Long Island	3590	10
\.


--
-- TOC entry 3642 (class 0 OID 16663)
-- Dependencies: 223
-- Data for Name: food_products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.food_products (food_id, product_id, quantity) FROM stdin;
\.


--
-- TOC entry 3639 (class 0 OID 16643)
-- Dependencies: 220
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (id, name, in_stock, unit) FROM stdin;
\.


--
-- TOC entry 3643 (class 0 OID 16744)
-- Dependencies: 224
-- Data for Name: tables; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tables (number, position_x, position_y, size_width, size_height, occupied) FROM stdin;
4	281.6666564941406	385.6666666666667	40	80	f
5	151.66665649414062	321.6666666666667	40	80	f
6	245.3333282470703	146.999994913737	60	70	f
\.


--
-- TOC entry 3635 (class 0 OID 16516)
-- Dependencies: 216
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, username, password, code, role) FROM stdin;
6	Sanzhar	$2a$10$Vf9F1FqBmuowmWbqUsreRO9Fc6Ekjw.jjWB9qqm02BaoY75zBaX9S	2290	admin
24	Owner	$2a$10$QPLVO5tbf8QYEQ6ajbbUP.AavHhHyCCr65ialJw9vhhjM0VhIYz8u	1215	owner
29	Sake	$2a$10$S.IaRFDq5Dpk1p7r9LcLEOTXnLZHkQsBN4rhSyXhTfMXKWD2xrPaq	4347	waiter
40	Lpojkhjk	$2a$10$D4.Jk4IQpLnUMh4/0zv8TegRHJ/gObSrDOIuzVAG9Ze92NRwE0gHi	9837	waiter
41	Baurzhan	$2a$10$7X9.Gul.xgaaGmrYLPm3wO4smcw3MQEmAQcrLjtMUpU6sOLo5do0K	5697	waiter
\.


--
-- TOC entry 3649 (class 0 OID 0)
-- Dependencies: 217
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categories_id_seq', 62, true);


--
-- TOC entry 3650 (class 0 OID 0)
-- Dependencies: 221
-- Name: food_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.food_id_seq', 12, true);


--
-- TOC entry 3651 (class 0 OID 0)
-- Dependencies: 219
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 1, true);


--
-- TOC entry 3652 (class 0 OID 0)
-- Dependencies: 215
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 42, true);


--
-- TOC entry 3477 (class 2606 OID 16605)
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- TOC entry 3481 (class 2606 OID 16657)
-- Name: food food_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food
    ADD CONSTRAINT food_pkey PRIMARY KEY (id);


--
-- TOC entry 3483 (class 2606 OID 16667)
-- Name: food_products food_products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_products
    ADD CONSTRAINT food_products_pkey PRIMARY KEY (food_id, product_id);


--
-- TOC entry 3479 (class 2606 OID 16649)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- TOC entry 3485 (class 2606 OID 16749)
-- Name: tables tables_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tables
    ADD CONSTRAINT tables_pkey PRIMARY KEY (number);


--
-- TOC entry 3469 (class 2606 OID 16690)
-- Name: users unique_code; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT unique_code UNIQUE (code);


--
-- TOC entry 3471 (class 2606 OID 16696)
-- Name: users unique_username; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT unique_username UNIQUE (username);


--
-- TOC entry 3473 (class 2606 OID 16524)
-- Name: users users_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_code_key UNIQUE (code);


--
-- TOC entry 3475 (class 2606 OID 16522)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3490 (class 2620 OID 16692)
-- Name: users generate_code_trigger; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER generate_code_trigger BEFORE INSERT ON public.users FOR EACH ROW EXECUTE FUNCTION public.generate_unique_code();


--
-- TOC entry 3486 (class 2606 OID 16606)
-- Name: categories categories_parent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.categories(id) ON DELETE CASCADE;


--
-- TOC entry 3487 (class 2606 OID 16658)
-- Name: food food_category_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food
    ADD CONSTRAINT food_category_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- TOC entry 3488 (class 2606 OID 16668)
-- Name: food_products food_products_food_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_products
    ADD CONSTRAINT food_products_food_id_fkey FOREIGN KEY (food_id) REFERENCES public.food(id);


--
-- TOC entry 3489 (class 2606 OID 16673)
-- Name: food_products food_products_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_products
    ADD CONSTRAINT food_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id);


-- Completed on 2024-10-25 19:50:03 +05

--
-- PostgreSQL database dump complete
--

